<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atual.Backup\Atual.Backup.csproj" />
    <ProjectReference Include="..\..\src\Atual.Backup.Core\Atual.Backup.Core.csproj" />
    <ProjectReference Include="..\..\src\Atual.Backup.Infrastructure\Atual.Backup.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Atual.Backup.Database\Atual.Backup.Database.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>